import type { AtcFeed } from "./atc-types";
import { FEED_TYPE_PRIORITY } from "./atc-types";
import { ATC_FEEDS, getFeedsByIcao } from "./atc-feeds";
import { AIRPORTS, type Airport } from "./airports";

// ── Constants ──────────────────────────────────────────────────────────

/** Approximate nautical miles per degree of latitude. */
const NM_PER_DEG = 60;

/** Maximum search radius in nautical miles for auto-feed discovery. */
const MAX_SEARCH_RADIUS_NM = 60;

// ── IATA → ICAO mapping ───────────────────────────────────────────────

/**
 * Common IATA → ICAO mapping for airports in the feed database.
 * Only includes airports that have ATC feeds to keep the map small.
 */
const IATA_TO_ICAO: Record<string, string> = {
  // United States
  JFK: "KJFK",
  LAX: "KLAX",
  ORD: "KORD",
  ATL: "KATL",
  DFW: "KDFW",
  DEN: "KDEN",
  SFO: "KSFO",
  LAS: "KLAS",
  MIA: "KMIA",
  EWR: "KEWR",
  SEA: "KSEA",
  BOS: "KBOS",
  MSP: "KMSP",
  PHX: "KPHX",
  DTW: "KDTW",
  FLL: "KFLL",
  IAD: "KIAD",
  CLT: "KCLT",
  DCA: "KDCA",
  HNL: "PHNL",
  ANC: "PANC",
  // Europe
  LHR: "EGLL",
  CDG: "LFPG",
  AMS: "EHAM",
  FRA: "EDDF",
  MAD: "LEMD",
  MUC: "EDDM",
  IST: "LTFM",
  LGW: "EGKK",
  BCN: "LEBL",
  FCO: "LIRF",
  ZRH: "LSZH",
  DUB: "EIDW",
  VIE: "LOWW",
  OSL: "ENGM",
  CPH: "EKCH",
  ARN: "ESSA",
  WAW: "EPWA",
  LIS: "LPPT",
  // Middle East
  DXB: "OMDB",
  DOH: "OTHH",
  JED: "OEJN",
  // Asia Pacific
  HND: "RJTT",
  NRT: "RJAA",
  SIN: "WSSS",
  HKG: "VHHH",
  ICN: "RKSI",
  BKK: "VTBS",
  KUL: "WMKK",
  DEL: "VIDP",
  BOM: "VABB",
  // Australia / Oceania
  SYD: "YSSY",
  MEL: "YMML",
  AKL: "NZAA",
  // Americas (non-US)
  YYZ: "CYYZ",
  YVR: "CYVR",
  MEX: "MMMX",
  GRU: "SBGR",
  EZE: "SAEZ",
  SCL: "SCEL",
  BOG: "SKBO",
  // Africa
  JNB: "FAOR",
  CAI: "HECA",
};

const ICAO_TO_IATA: Record<string, string> = {};
for (const [iata, icao] of Object.entries(IATA_TO_ICAO)) {
  ICAO_TO_IATA[icao] = iata;
}

// ── Full-DB lookup tables (lazy) ──────────────────────────────────────
//
// The hand-maintained `IATA_TO_ICAO` above only covers airports that LiveATC
// carries feeds for (~60 airports). For the rest of the 8000+ airport DB we
// fall back to the enriched `Airport.icao` field generated by
// scripts/enrich-airports.mjs. Building the reverse maps once and caching
// keeps lookups O(1) without paying the ~9K-entry cost on import.

let FULL_IATA_TO_ICAO: Map<string, string> | null = null;
let FULL_ICAO_TO_IATA: Map<string, string> | null = null;

function resetFullMaps(): void {
  FULL_IATA_TO_ICAO = null;
  FULL_ICAO_TO_IATA = null;
}

function hasBuiltFullMaps(): boolean {
  return FULL_IATA_TO_ICAO !== null && FULL_ICAO_TO_IATA !== null;
}

function buildFullMaps(): void {
  if (FULL_IATA_TO_ICAO && FULL_ICAO_TO_IATA) return;
  const iataMap = new Map<string, string>();
  const icaoMap = new Map<string, string>();
  for (const a of AIRPORTS) {
    if (!a.icao) continue;
    const iata = a.iata.toUpperCase();
    const icao = a.icao.toUpperCase();
    // First-writer wins — OurAirports occasionally has duplicate IATAs for
    // decommissioned airports. Our DB is already de-duped, so this is rare.
    if (!iataMap.has(iata)) iataMap.set(iata, icao);
    if (!icaoMap.has(icao)) icaoMap.set(icao, iata);
  }
  FULL_IATA_TO_ICAO = iataMap;
  FULL_ICAO_TO_IATA = icaoMap;
}

/**
 * Convert IATA to ICAO. Checks the curated feed-database map first (so LiveATC
 * callsign conventions like `KJFK` over `KJFK`-variant are preserved), then
 * falls back to the full OurAirports-enriched airport DB (~8500 airports).
 */
export function iataToIcao(iata: string): string | null {
  const upper = iata.toUpperCase();
  const curated = IATA_TO_ICAO[upper];
  if (curated) return curated;
  buildFullMaps();
  return FULL_IATA_TO_ICAO!.get(upper) ?? null;
}

/**
 * Convert ICAO to IATA. Curated map first, then full DB fallback.
 */
export function icaoToIata(icao: string): string | null {
  const upper = icao.toUpperCase();
  const curated = ICAO_TO_IATA[upper];
  if (curated) return curated;
  buildFullMaps();
  return FULL_ICAO_TO_IATA!.get(upper) ?? null;
}

export const __internals = {
  resetFullMaps,
  hasBuiltFullMaps,
};

/** ICAO codes of airports that have ATC feeds. */
const ICAO_SET = new Set(Object.keys(ATC_FEEDS));

/** Precomputed list of airports that have ATC feeds. */
const ATC_AIRPORTS: Airport[] = AIRPORTS.filter((a) => {
  return !!a.icao && ICAO_SET.has(a.icao.toUpperCase());
});

// ── Lookup Functions ───────────────────────────────────────────────────

/**
 * Simple distance approximation in nautical miles (good enough for feed lookup).
 * Uses equirectangular approximation — accurate to ~1% within 60nm.
 */
function approxDistanceNm(
  lat1: number,
  lng1: number,
  lat2: number,
  lng2: number,
): number {
  const dLat = (lat2 - lat1) * NM_PER_DEG;
  const dLng =
    (lng2 - lng1) *
    NM_PER_DEG *
    Math.cos(((lat1 + lat2) / 2) * (Math.PI / 180));
  return Math.sqrt(dLat * dLat + dLng * dLng);
}

export type NearbyAtcResult = {
  /** Airport ICAO code */
  icao: string;
  /** Airport IATA code (if known) */
  iata: string | null;
  /** Airport name */
  name: string;
  /** Distance in nautical miles */
  distanceNm: number;
  /** Available ATC feeds, sorted by type priority */
  feeds: AtcFeed[];
};

/**
 * Find airports with ATC feeds near a given latitude/longitude.
 * Returns results sorted by distance (nearest first).
 *
 * @param lat Latitude in degrees
 * @param lng Longitude in degrees
 * @param radiusNm Search radius in nautical miles (default: 60)
 * @param limit Maximum results to return (default: 5)
 */
export function findNearbyAtcFeeds(
  lat: number,
  lng: number,
  radiusNm: number = MAX_SEARCH_RADIUS_NM,
  limit: number = 5,
): NearbyAtcResult[] {
  const clampedRadius = Math.min(radiusNm, MAX_SEARCH_RADIUS_NM);
  const results: NearbyAtcResult[] = [];

  for (const airport of ATC_AIRPORTS) {
    const dist = approxDistanceNm(lat, lng, airport.lat, airport.lng);
    if (dist > clampedRadius) continue;

    const icao = airport.icao?.toUpperCase() ?? iataToIcao(airport.iata);
    if (!icao) continue;

    const feeds = getFeedsByIcao(icao).sort(
      (a, b) => FEED_TYPE_PRIORITY[a.type] - FEED_TYPE_PRIORITY[b.type],
    );

    if (feeds.length === 0) continue;

    results.push({
      icao,
      iata: airport.iata,
      name: airport.name,
      distanceNm: Math.round(dist * 10) / 10,
      feeds,
    });
  }

  results.sort((a, b) => a.distanceNm - b.distanceNm);
  return results.slice(0, limit);
}

/**
 * Find the single nearest airport with ATC feeds.
 * Convenience wrapper around findNearbyAtcFeeds.
 */
export function findNearestAtcFeed(
  lat: number,
  lng: number,
): NearbyAtcResult | null {
  const results = findNearbyAtcFeeds(lat, lng, MAX_SEARCH_RADIUS_NM, 1);
  return results[0] ?? null;
}

/**
 * Look up ATC feeds by IATA or ICAO code.
 */
export function lookupAtcFeeds(code: string): AtcFeed[] {
  const upper = code.toUpperCase();

  // Try ICAO first
  const icaoFeeds = getFeedsByIcao(upper);
  if (icaoFeeds.length > 0) return icaoFeeds;

  // Try IATA → ICAO
  const icao = iataToIcao(upper);
  if (icao) return getFeedsByIcao(icao);

  return [];
}
